<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Currencies' => '',
  'Currency Rate' => '',
  'Currency Rates' => '',
  'Currency code' => '',
  'Currency from' => '',
  'Currency source' => '',
  'Currency to' => '',
  'Date' => '',
  'Fcrn Currencies' => '',
  'Fcrn Currency' => '',
  'FcrnCurrency.fcrn_code' => '',
  'FcrnCurrency.fcrn_id' => '',
  'FcrnId' => '',
  'Fcrt Currency Rate' => '',
  'Fcrt Currency Rates' => '',
  'FcrtCurrencyRate.fcrt_date' => '',
  'FcrtCurrencyRate.fcrt_fcrn_id' => '',
  'FcrtCurrencyRate.fcrt_fcsr_id' => '',
  'FcrtCurrencyRate.fcrt_id' => '',
  'FcrtCurrencyRate.fcrt_rate' => '',
  'FcrtCurrencyRate.fcrt_to_fcrn_id' => '',
  'FcrtId' => '',
  'Fcsr Courrency Source' => '',
  'Fcsr Courrency Sources' => '',
  'FcsrCourrencySource.fcsr_id' => '',
  'FcsrCourrencySource.fcsr_name' => '',
  'FcsrCourrencySource.fcsr_notes' => '',
  'FcsrId' => '',
  'Notes' => '',
  'Rate' => '',
  'Source' => '',
);
